[phases.setup]
nixPkgs = ["python3", "nodejs_20"]

[phases.frontend]
dependsOn = ["setup"]
cmds = ["npm --prefix frontend ci", "npm --prefix frontend run build"]

[start]
cmd = "gunicorn canopy.app:app"
