"""add rating schema

Revision ID: 10ce20f0c80a
Revises: cddf685e3ae4
Create Date: 2026-08-11 16:30:18.704015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10ce20f0c80a'
down_revision: Union[str, None] = 'cddf685e3ae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('polarity', sa.String(), nullable=False),
    sa.Column('mapped_features', sa.JSON(), nullable=False),
    sa.Column('anchor_aware', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('anchors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('ideal_minutes', sa.Integer(), nullable=False),
    sa.Column('limit_minutes', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['raters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('judgments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rater_id', sa.String(), nullable=False),
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('feature_set_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['rater_id'], ['raters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listing_features',
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('feature_set_version', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('lot_acreage', sa.Float(), nullable=True),
    sa.Column('lot_depth_ft', sa.Float(), nullable=True),
    sa.Column('lot_width_ft', sa.Float(), nullable=True),
    sa.Column('protected_perimeter_ratio', sa.Float(), nullable=True),
    sa.Column('abuts_water', sa.Boolean(), nullable=True),
    sa.Column('abuts_marsh_wetland', sa.Boolean(), nullable=True),
    sa.Column('abuts_park_public', sa.Boolean(), nullable=True),
    sa.Column('abuts_conservation_easement', sa.Boolean(), nullable=True),
    sa.Column('abuts_buildable_private', sa.Boolean(), nullable=True),
    sa.Column('rear_open_distance_ft', sa.Float(), nullable=True),
    sa.Column('wetland_pct_of_parcel', sa.Float(), nullable=True),
    sa.Column('flood_zone', sa.String(), nullable=True),
    sa.Column('parcel_canopy_pct', sa.Float(), nullable=True),
    sa.Column('neighborhood_canopy_pct', sa.Float(), nullable=True),
    sa.Column('canopy_delta', sa.Float(), nullable=True),
    sa.Column('median_year_built_buffer', sa.Integer(), nullable=True),
    sa.Column('canopy_age_proxy', sa.Float(), nullable=True),
    sa.Column('fronting_road_class', sa.String(), nullable=True),
    sa.Column('dist_to_arterial_m', sa.Float(), nullable=True),
    sa.Column('is_cul_de_sac', sa.Boolean(), nullable=True),
    sa.Column('is_dead_end', sa.Boolean(), nullable=True),
    sa.Column('through_traffic_proxy', sa.Float(), nullable=True),
    sa.Column('front_setback_ft', sa.Float(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('sqft', sa.Integer(), nullable=True),
    sa.Column('beds', sa.Float(), nullable=True),
    sa.Column('baths', sa.Float(), nullable=True),
    sa.Column('stories', sa.Float(), nullable=True),
    sa.Column('arch_style', sa.String(), nullable=True),
    sa.Column('arch_style_confidence', sa.Float(), nullable=True),
    sa.Column('exterior_material', sa.String(), nullable=True),
    sa.Column('has_front_porch', sa.Boolean(), nullable=True),
    sa.Column('garage_type', sa.String(), nullable=True),
    sa.Column('visible_renovation_recency', sa.String(), nullable=True),
    sa.Column('vision_computed_at', sa.DateTime(), nullable=True),
    sa.Column('list_price', sa.Float(), nullable=True),
    sa.Column('price_per_sqft', sa.Float(), nullable=True),
    sa.Column('days_on_market', sa.Integer(), nullable=True),
    sa.Column('price_cut_count', sa.Integer(), nullable=True),
    sa.Column('hoa_fee_monthly', sa.Float(), nullable=True),
    sa.Column('imputed_fields', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('listing_id', 'feature_set_version')
    )
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rater_id', sa.String(), nullable=False),
    sa.Column('feature_set_version', sa.String(), nullable=False),
    sa.Column('trained_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('n_pairs', sa.Integer(), nullable=False),
    sa.Column('coefficients', sa.JSON(), nullable=False),
    sa.Column('coef_ci', sa.JSON(), nullable=True),
    sa.Column('scaler_params', sa.JSON(), nullable=False),
    sa.Column('basis_config', sa.JSON(), nullable=True),
    sa.Column('holdout_accuracy', sa.Float(), nullable=True),
    sa.Column('baseline_accuracy', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['rater_id'], ['raters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pairwise_comparisons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rater_id', sa.String(), nullable=False),
    sa.Column('listing_a', sa.String(), nullable=False),
    sa.Column('listing_b', sa.String(), nullable=False),
    sa.Column('winner', sa.String(), nullable=False),
    sa.Column('selection_strategy', sa.String(), nullable=True),
    sa.Column('feature_set_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_a'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['listing_b'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['rater_id'], ['raters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('judgment_anchors',
    sa.Column('judgment_id', sa.Integer(), nullable=False),
    sa.Column('anchor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anchor_id'], ['anchors.id'], ),
    sa.ForeignKeyConstraint(['judgment_id'], ['judgments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('judgment_id', 'anchor_id')
    )
    op.create_table('judgment_tags',
    sa.Column('judgment_id', sa.Integer(), nullable=False),
    sa.Column('tag_code', sa.String(), nullable=False),
    sa.Column('free_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['judgment_id'], ['judgments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_code'], ['tags.code'], ),
    sa.PrimaryKeyConstraint('judgment_id', 'tag_code')
    )
    op.create_table('listing_anchor_times',
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('anchor_id', sa.Integer(), nullable=False),
    sa.Column('drive_minutes', sa.Float(), nullable=True),
    sa.Column('straight_line_km', sa.Float(), nullable=True),
    sa.Column('is_proxy', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anchor_id'], ['anchors.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('listing_id', 'anchor_id')
    )
    op.create_table('preference_scores',
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('display_score', sa.Float(), nullable=False),
    sa.Column('pred_variance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ),
    sa.PrimaryKeyConstraint('listing_id', 'model_run_id')
    )
    # ### end Alembic commands ###

    _seed_raters_and_tags()


# Seed data below is transcribed from docs/RatingUI.jsx's NEG_TAGS/POS_TAGS
# (the v2 taxonomy -- UI_SPEC.md explicitly wins over the v1 list in
# FEATURE_SCHEMA.md §3 where they disagree). Rater ids match the UI copy
# ("Zach"/"Partner"), not FEATURE_SCHEMA.md's illustrative 'wife'.

raters_table = sa.table(
    "raters",
    sa.column("id", sa.String),
    sa.column("display_name", sa.String),
)

tags_table = sa.table(
    "tags",
    sa.column("code", sa.String),
    sa.column("label", sa.String),
    sa.column("polarity", sa.String),
    sa.column("mapped_features", sa.JSON),
    sa.column("anchor_aware", sa.Boolean),
    sa.column("active", sa.Boolean),
)

NEG_TAGS = [
    ("road_too_busy", "Too close to a busy road", ["fronting_road_class"], False),
    ("lot_too_open", "Lot too open", ["parcel_canopy_pct"], False),
    ("street_too_bare", "Street lacks canopy", ["neighborhood_canopy_pct"], False),
    ("backs_to_buildable", "Someone can build behind it", ["protected_perimeter_ratio"], False),
    ("not_private", "Doesn't feel private", ["rear_open_distance_ft"], False),
    ("wrong_architecture", "Wrong style", ["arch_style"], False),
    ("too_far", "Too far from where we go", ["anchor_drive_times"], True),
    ("flood_risk", "Flood exposure", ["flood_zone"], False),
    ("lot_too_small", "Lot too small", ["lot_acreage"], False),
    ("overpriced", "Not worth the price", ["price_per_sqft"], False),
    ("other_no", "Something else", [], False),
]

POS_TAGS = [
    ("abuts_protected", "Abuts protected land", ["protected_perimeter_ratio"], False),
    ("feels_private", "Feels private", ["rear_open_distance_ft"], False),
    ("mature_canopy", "Beautiful trees on the lot", ["parcel_canopy_pct"], False),
    ("wooded_street", "Whole street is wooded", ["neighborhood_canopy_pct"], False),
    ("quiet_street", "Quiet street", ["fronting_road_class"], False),
    ("water_adjacency", "Water or marsh", ["abuts_water"], False),
    ("love_architecture", "Love the style", ["arch_style"], False),
    ("period_character", "Real character", ["year_built"], False),
    ("big_lot", "Great lot size", ["lot_acreage"], False),
    ("well_placed", "Well placed for us", ["anchor_drive_times"], True),
    ("good_value", "Priced well", ["price_per_sqft"], False),
    ("other_yes", "Something else", [], False),
]


def _seed_raters_and_tags() -> None:
    op.bulk_insert(raters_table, [
        {"id": "zach", "display_name": "Zach"},
        {"id": "andrea", "display_name": "Andrea"},
    ])
    op.bulk_insert(tags_table, [
        {"code": code, "label": label, "polarity": "negative",
         "mapped_features": features, "anchor_aware": anchor_aware, "active": True}
        for code, label, features, anchor_aware in NEG_TAGS
    ] + [
        {"code": code, "label": label, "polarity": "positive",
         "mapped_features": features, "anchor_aware": anchor_aware, "active": True}
        for code, label, features, anchor_aware in POS_TAGS
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preference_scores')
    op.drop_table('listing_anchor_times')
    op.drop_table('judgment_tags')
    op.drop_table('judgment_anchors')
    op.drop_table('pairwise_comparisons')
    op.drop_table('model_runs')
    op.drop_table('listing_features')
    op.drop_table('judgments')
    op.drop_table('anchors')
    op.drop_table('tags')
    op.drop_table('raters')
    # ### end Alembic commands ###
