"""add resolved_address to anchors

Revision ID: 341699da3cfb
Revises: afcfafc39215
Create Date: 2026-08-12 14:32:04.311384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '341699da3cfb'
down_revision: Union[str, None] = 'afcfafc39215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anchors', sa.Column('resolved_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anchors', 'resolved_address')
    # ### end Alembic commands ###
