"""retire hard filter and subagent flag columns

Revision ID: afcfafc39215
Revises: 10ce20f0c80a
Create Date: 2026-08-12 07:32:50.984366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afcfafc39215'
down_revision: Union[str, None] = '10ce20f0c80a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scores', 'subagent_flag_ok')
    op.drop_column('scores', 'passed_filter')
    op.drop_column('scores', 'filter_reasons')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('filter_reasons', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('scores', sa.Column('passed_filter', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('scores', sa.Column('subagent_flag_ok', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
