"""initial schema

Revision ID: cddf685e3ae4
Revises: 
Create Date: 2026-08-10 13:14:38.125262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cddf685e3ae4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('formatted_address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('zip_code', sa.String(), nullable=False),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('property_type', sa.String(), nullable=True),
    sa.Column('lot_size_sqft', sa.Float(), nullable=True),
    sa.Column('square_footage', sa.Float(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('listed_date', sa.DateTime(), nullable=True),
    sa.Column('removed_date', sa.DateTime(), nullable=True),
    sa.Column('last_seen_date', sa.DateTime(), nullable=True),
    sa.Column('mls_name', sa.String(), nullable=True),
    sa.Column('mls_number', sa.String(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_ingested', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_zip_code'), 'listings', ['zip_code'], unique=False)
    op.create_table('digest_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parcels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=True),
    sa.Column('geometry_geojson', sa.JSON(), nullable=True),
    sa.Column('adjacent_water', sa.Boolean(), nullable=False),
    sa.Column('adjacent_park_or_conservation', sa.Boolean(), nullable=False),
    sa.Column('adjacent_county_or_city_owned', sa.Boolean(), nullable=False),
    sa.Column('flood_zone', sa.String(), nullable=True),
    sa.Column('wetland_overlay', sa.Boolean(), nullable=False),
    sa.Column('raw_gis', sa.JSON(), nullable=True),
    sa.Column('enriched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('canopy_pct', sa.Float(), nullable=True),
    sa.Column('old_growth_proxy_score', sa.Float(), nullable=True),
    sa.Column('passed_filter', sa.Boolean(), nullable=False),
    sa.Column('filter_reasons', sa.JSON(), nullable=True),
    sa.Column('subagent_flag_ok', sa.Boolean(), nullable=True),
    sa.Column('subagent_rationale', sa.String(), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('parcels')
    op.drop_table('digest_log')
    op.drop_index(op.f('ix_listings_zip_code'), table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
